//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrepsinioLyga
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rungtynės
    {
        public int Id { get; set; }
        public int Arena { get; set; }
        public int Žiūrovai { get; set; }
        public decimal Pajamos { get; set; }
        public int Namai { get; set; }
        public int Svečiai { get; set; }
        public int NTaškai { get; set; }
        public int STaškai { get; set; }
    
        public virtual Arena Arena1 { get; set; }
        public virtual Komanda Komanda { get; set; }
        public virtual Komanda Komanda1 { get; set; }
    }
}
